"""Seed the database with realistic NYC commercial real estate leads."""

from datetime import date
from core.database import Database
from core.models import EnrichedLead


def _lead(**kw) -> EnrichedLead:
    """Shortcut to create an EnrichedLead with defaults."""
    kw.setdefault("pipeline_stage", "NEW")
    kw.setdefault("company_type", "CRE_OPERATOR")
    kw.setdefault("social_links", {})
    kw.setdefault("recent_news", [])
    kw.setdefault("current_it_provider", None)
    kw.setdefault("linkedin_url", None)
    kw.setdefault("phone", None)
    kw.setdefault("num_employees", None)
    kw.setdefault("num_tenants", None)
    kw.setdefault("year_built", None)
    kw.setdefault("floors", None)
    kw.setdefault("sqft", None)
    kw.setdefault("building_isp", None)
    kw.setdefault("available_isps", [])
    kw.setdefault("equipment", {})
    kw.setdefault("building_summary", "")
    kw.setdefault("tech_signals", [])
    kw.setdefault("qualification_notes", "")
    kw.setdefault("score", 50)
    kw.setdefault("discovery_date", date(2026, 4, 13))
    kw.setdefault("sources", ["web_scraper"])
    return EnrichedLead(**kw)


# =============================================================================
# MANHATTAN — 25 leads
# =============================================================================
MANHATTAN = [
    _lead(
        company_name="JLL NYC Office",
        contact_name="Rebecca Liu", contact_title="VP Digital Transformation",
        email="r.liu@jll.com", phone="(212) 812-5700",
        website="https://jll.com",
        address="330 Madison Avenue, New York, NY 10017",
        building_type="Class A Office", sqft=850000, num_tenants=38,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=1963, floors=42, num_employees=220,
        building_isp="Zayo", available_isps=["Zayo", "Verizon Fios", "Pilot Fiber"],
        equipment={"hvac": "Trane CenTraVac", "elevator": "Otis Gen3 — 18 cabs", "security": "Kastle Systems", "bms": "Johnson Controls Metasys", "network_infrastructure": "Cat6 risers, MMF backbone"},
        building_summary="Class A office in Midtown East. 42 floors, 850K sqft. JLL manages building ops and is exploring tenant WiFi-as-a-service revenue model.",
        current_it_provider="Cognizant", tech_signals=["tenant WiFi monetization", "smart building analytics", "SD-WAN evaluation"],
        recent_news=["JLL launches PropTech accelerator", "Signed 3 new anchor tenants"],
        sources=["linkedin", "costar", "nyc_opendata"], score=94,
        qualification_notes="Big Three firm. VP actively exploring WiFi-as-revenue. Multi-building portfolio opportunity.",
    ),
    _lead(
        company_name="CBRE Asset Services",
        contact_name="Marcus Johnson", contact_title="Head of Building Experience",
        email="marcus.johnson@cbre.com", phone="(212) 984-8100",
        website="https://cbre.com",
        address="200 Park Avenue, New York, NY 10166",
        building_type="Class A+ Office", sqft=1500000, num_tenants=52,
        borough="Manhattan", neighborhood="Midtown",
        year_built=1963, floors=59, num_employees=310,
        building_isp="Crown Castle Fiber", available_isps=["Crown Castle Fiber", "Verizon Fios", "Zayo", "Cogent"],
        equipment={"hvac": "Daikin VRV IV", "elevator": "Schindler PORT — 32 cabs", "security": "Genetec Security Center", "bms": "Siemens Desigo CC", "network_infrastructure": "SMF backbone, Cisco Nexus 9000"},
        building_summary="MetLife Building (200 Park). 59 floors, 1.5M sqft. CBRE manages building experience program. Trophy asset with major tech upgrade budget.",
        current_it_provider="Accenture", tech_signals=["tenant experience platform", "5G DAS deployment", "digital twin"],
        sources=["linkedin", "costar", "news"], score=96,
        qualification_notes="Big Three. Head of Building Experience wants to monetize connectivity. $2M+ annual opportunity.",
    ),
    _lead(
        company_name="Cushman & Wakefield NYC",
        contact_name="Diana Patel", contact_title="Director of Asset Management",
        email="diana.patel@cushwake.com", phone="(212) 841-7500",
        website="https://cushmanwakefield.com",
        address="1290 Avenue of the Americas, New York, NY 10104",
        building_type="Class A Office", sqft=720000, num_tenants=30,
        borough="Manhattan", neighborhood="Midtown",
        year_built=1963, floors=43, num_employees=150,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Pilot Fiber"],
        equipment={"hvac": "Carrier AquaEdge 19XR", "elevator": "ThyssenKrupp — 20 cabs", "security": "LenelS2 OnGuard", "bms": "Honeywell Niagara 4", "network_infrastructure": "Cat6a horizontal, MMF backbone"},
        building_summary="Class A office tower on 6th Ave. 43 floors, 720K sqft. C&W managing property and tenant experience initiatives. Exploring NOI enhancement through tech services.",
        tech_signals=["NOI enhancement study", "tenant WiFi consolidation", "lobby digital signage"],
        sources=["linkedin", "costar"], score=91,
        qualification_notes="Big Three. Director focused on NOI enhancement through tech revenue streams.",
    ),
    _lead(
        company_name="Colliers International NYC",
        contact_name="Kevin O'Brien", contact_title="SVP Property Management",
        email="kevin.obrien@colliers.com", phone="(212) 716-3500",
        website="https://colliers.com",
        address="10 Hudson Yards, New York, NY 10001",
        building_type="Class A Office", sqft=1700000, num_tenants=25,
        borough="Manhattan", neighborhood="Hudson Yards",
        year_built=2016, floors=52, num_employees=200,
        building_isp="Zayo", available_isps=["Zayo", "Pilot Fiber", "Crown Castle Fiber", "Verizon Fios"],
        equipment={"hvac": "Trane CenTraVac centrifugal", "elevator": "Kone UltraRope — 28 cabs", "security": "Evolv weapons detection + HID mobile", "bms": "Johnson Controls Metasys", "network_infrastructure": "SMF backbone, Cat6a, Aruba CX switches"},
        building_summary="Hudson Yards flagship. 52 floors, 1.7M sqft. Smart building with full BMS integration. Colliers exploring managed connectivity as tenant amenity.",
        current_it_provider="Multiple MSPs", tech_signals=["consolidating MSP vendors", "managed WiFi RFP", "IoT sensor deployment"],
        sources=["linkedin", "news", "costar"], score=90,
        qualification_notes="Big Three. Looking to consolidate from 4 MSPs to 1. Smart building ready.",
    ),
    _lead(
        company_name="Savills NYC",
        contact_name="Priya Sharma", contact_title="Head of Workplace Solutions",
        email="psharma@savills.us", phone="(212) 326-1000",
        website="https://savills.us",
        address="399 Park Avenue, New York, NY 10022",
        building_type="Class A Office", sqft=500000, num_tenants=20,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=1961, floors=39, num_employees=95,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Lightpath"],
        equipment={"hvac": "York YK centrifugal", "elevator": "Otis 2000E — 12 cabs", "security": "AMAG Symmetry", "bms": "Schneider EcoStruxure", "network_infrastructure": "Cat6 risers, Juniper switches"},
        building_summary="Class A tower on Park Ave. 39 floors, 500K sqft. Savills managing workplace tech strategy. Building needs infrastructure refresh.",
        tech_signals=["workplace experience platform", "cable plant upgrade", "access control modernization"],
        sources=["linkedin", "costar"], score=82,
        qualification_notes="Big Three. Workplace Solutions team evaluating full tech refresh.",
    ),
    _lead(
        company_name="Brookfield Property Partners",
        contact_name="Sarah Chen", contact_title="VP of Operations",
        email="s.chen@brookfieldproperties.com", phone="(212) 417-7063",
        website="https://brookfieldproperties.com",
        address="250 Vesey Street, New York, NY 10281",
        building_type="Class A Office", sqft=1200000, num_tenants=45,
        borough="Manhattan", neighborhood="Battery Park City",
        year_built=1986, floors=51, num_employees=320,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Pilot Fiber", "Zayo"],
        equipment={"hvac": "Trane Intellipak (2019 retrofit)", "elevator": "Otis Gen3 — 24 cabs", "security": "Kastle Systems access control + CCTV", "bms": "Siemens Desigo CC", "network_infrastructure": "Cat6a risers, MMF backbone, Cisco Meraki switches"},
        building_summary="Class A office tower in Battery Park City. 51 floors, 1.2M sqft. Brookfield Place campus. LEED Gold certified. Major tenant WiFi consolidation opportunity.",
        current_it_provider="Cognizant", tech_signals=["RFP for network upgrade", "SD-WAN evaluation", "tenant WiFi revenue study"],
        sources=["linkedin", "costar", "nyc_opendata"], score=92,
        qualification_notes="Major CRE operator. Active RFP for network infrastructure. Multi-building Brookfield Place campus.",
    ),
    _lead(
        company_name="SL Green Realty",
        contact_name="David Park", contact_title="SVP Building Operations",
        email="d.park@slgreen.com", phone="(212) 594-2700",
        website="https://slgreen.com",
        address="One Vanderbilt Avenue, New York, NY 10017",
        building_type="Class A+ Office", sqft=1700000, num_tenants=28,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=2020, floors=77, num_employees=180,
        building_isp="Zayo", available_isps=["Zayo", "Crown Castle Fiber", "Verizon Fios", "Pilot Fiber", "Cogent"],
        equipment={"hvac": "Daikin VRV IV — full building", "elevator": "Kone UltraRope — 33 cabs, destination dispatch", "security": "Evolv weapons detection + HID mobile access", "bms": "Johnson Controls Metasys", "network_infrastructure": "SMF backbone, Cat6a horizontal, Aruba CX switches"},
        building_summary="NYC's newest supertall office tower. 77 floors, 1.7M sqft. LEED Platinum, WELL certified. State-of-the-art smart building. Revenue-as-a-Service model potential.",
        current_it_provider="JLL Technologies", tech_signals=["smart building analytics", "digital twin initiative", "5G DAS deployment"],
        sources=["costar", "nyc_opendata", "news"], score=95,
        qualification_notes="Trophy asset with aggressive tech roadmap. Budget approved for smart building platform.",
    ),
    _lead(
        company_name="Vornado Realty Trust",
        contact_name="Thomas Mitchell", contact_title="Director of Engineering",
        email="t.mitchell@vno.com", phone="(212) 894-7000",
        website="https://vno.com",
        address="PENN 1, 1 Penn Plaza, New York, NY 10119",
        building_type="Class A Office", sqft=2400000, num_tenants=60,
        borough="Manhattan", neighborhood="Penn District",
        year_built=1972, floors=57, num_employees=280,
        building_isp="Crown Castle Fiber", available_isps=["Crown Castle Fiber", "Zayo", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "York centrifugal (2022 replacement)", "elevator": "Schindler 7000 — 26 cabs", "security": "Genetec Security Center", "bms": "Siemens Desigo CC", "network_infrastructure": "Cat6 risers, MMF backbone, Cisco Catalyst switches"},
        building_summary="Massive office complex in Penn District. 57 floors, 2.4M sqft. $450M renovation underway including full tech infrastructure overhaul. Prime Revenue-as-a-Service opportunity.",
        current_it_provider="Presidio", tech_signals=["$450M renovation", "full network redesign", "tenant experience platform"],
        sources=["news", "costar", "nyc_opendata"], score=93,
        qualification_notes="$450M renovation = massive infrastructure opportunity. 60+ tenants for WiFi revenue model.",
    ),
    _lead(
        company_name="Tishman Speyer",
        contact_name="Angela Wu", contact_title="VP of PropTech",
        email="a.wu@tishmanspeyer.com", phone="(212) 715-0300",
        website="https://tishmanspeyer.com",
        address="45 Rockefeller Plaza, New York, NY 10111",
        building_type="Class A Office", sqft=900000, num_tenants=40,
        borough="Manhattan", neighborhood="Midtown",
        year_built=1950, floors=40, num_employees=170,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Zayo", "Crown Castle Fiber"],
        equipment={"hvac": "Carrier 30XA air-cooled", "elevator": "Otis Gen3 — 16 cabs", "security": "HID mobile access + Verkada", "bms": "Honeywell Niagara 4", "network_infrastructure": "Cat6a, SMF backbone, Arista 7000"},
        building_summary="Rockefeller Center building. 40 floors, 900K sqft. Tishman Speyer's ZO platform enables tenant WiFi monetization. Looking for infrastructure partner.",
        current_it_provider="In-house ZO platform", tech_signals=["ZO platform expansion", "tenant WiFi tiering", "IoT building sensors"],
        sources=["linkedin", "news", "costar"], score=88,
        qualification_notes="PropTech-forward operator with ZO platform. Need infrastructure partner for WiFi-as-a-service.",
    ),
    _lead(
        company_name="Silverstein Properties",
        contact_name="Rachel Goldstein", contact_title="Director of Smart Building",
        email="r.goldstein@silversteinproperties.com", phone="(212) 490-0666",
        website="https://silversteinproperties.com",
        address="7 World Trade Center, New York, NY 10007",
        building_type="Class A+ Office", sqft=1700000, num_tenants=30,
        borough="Manhattan", neighborhood="Financial District",
        year_built=2006, floors=52, num_employees=200,
        building_isp="Zayo", available_isps=["Zayo", "Crown Castle Fiber", "Pilot Fiber", "Cogent"],
        equipment={"hvac": "Trane CenTraVac", "elevator": "Schindler PORT — 24 cabs", "security": "Evolv Express + HID Origo", "bms": "Johnson Controls OpenBlue", "network_infrastructure": "SMF backbone, Cat6a, Cisco Meraki campus"},
        building_summary="WTC campus. 52 floors, 1.7M sqft. Smart building with full IoT deployment. Exploring managed connectivity revenue across WTC portfolio.",
        tech_signals=["WTC campus WiFi consolidation", "tenant portal upgrade", "cybersecurity assessment"],
        sources=["costar", "news", "nyc_opendata"], score=91,
        qualification_notes="WTC portfolio — multi-building campus opportunity. Director of Smart Building actively sourcing.",
    ),
    _lead(
        company_name="Related Companies",
        contact_name="Brian Torres", contact_title="Head of Digital Infrastructure",
        email="b.torres@related.com", phone="(212) 801-1000",
        website="https://related.com",
        address="30 Hudson Yards, New York, NY 10001",
        building_type="Class A+ Office", sqft=2600000, num_tenants=35,
        borough="Manhattan", neighborhood="Hudson Yards",
        year_built=2019, floors=90, num_employees=350,
        building_isp="Zayo", available_isps=["Zayo", "Pilot Fiber", "Crown Castle Fiber", "Verizon Fios"],
        equipment={"hvac": "Trane CenTraVac (AI-optimized)", "elevator": "Kone TWIN — 40 cabs", "security": "Genetec + thermal cameras", "bms": "Siemens Desigo with AI", "network_infrastructure": "SMF backbone, Cat6a, Cisco Nexus 9000"},
        building_summary="Hudson Yards flagship supertall. 90 floors, 2.6M sqft. Full smart building with AI BMS. Revenue-as-a-Service model already in pilot for tenant WiFi.",
        current_it_provider="Multiple MSPs", tech_signals=["WiFi revenue pilot", "consolidating MSPs", "ESG reporting platform"],
        sources=["linkedin", "costar", "news"], score=97,
        qualification_notes="Hudson Yards campus. Already piloting WiFi revenue model. Looking for single MSP partner. $3M+/year opportunity.",
    ),
    _lead(
        company_name="Paramount Group",
        contact_name="Jennifer Lee", contact_title="Operations Manager",
        email="j.lee@paramount-group.com", phone="(212) 237-3100",
        website="https://paramount-group.com",
        address="1633 Broadway, New York, NY 10019",
        building_type="Class A Office", sqft=2600000, num_tenants=55,
        borough="Manhattan", neighborhood="Midtown West",
        year_built=1972, floors=48, num_employees=150,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Zayo"],
        equipment={"hvac": "York centrifugal", "elevator": "Otis 2000E — 22 cabs", "security": "LenelS2 OnGuard", "bms": "Schneider EcoStruxure", "network_infrastructure": "Cat6 risers, Juniper EX switches"},
        building_summary="Large Class A tower near Columbus Circle. 48 floors, 2.6M sqft. Aging network infrastructure. 55 tenants = strong WiFi revenue potential.",
        tech_signals=["cable plant refresh", "tenant WiFi interest", "access control upgrade"],
        sources=["costar", "nyc_opendata"], score=79,
        qualification_notes="55 tenants for WiFi revenue model. Aging infrastructure needs full refresh.",
    ),
    _lead(
        company_name="Boston Properties (BXP)",
        contact_name="Daniel Kim", contact_title="Regional VP Technology",
        email="d.kim@bxp.com", phone="(212) 905-5500",
        website="https://bxp.com",
        address="599 Lexington Avenue, New York, NY 10022",
        building_type="Class A Office", sqft=1050000, num_tenants=42,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=1986, floors=50, num_employees=160,
        building_isp="Crown Castle Fiber", available_isps=["Crown Castle Fiber", "Verizon Fios", "Pilot Fiber"],
        equipment={"hvac": "Trane Intellipak", "elevator": "Schindler 7000 — 20 cabs", "security": "Kastle Systems", "bms": "Johnson Controls Metasys", "network_infrastructure": "Cat6a risers, SMF backbone, Arista switches"},
        building_summary="Class A office at 599 Lex. 50 floors, 1.05M sqft. BXP evaluating managed connectivity across NYC portfolio.",
        current_it_provider="Convergys", tech_signals=["portfolio WiFi strategy", "tenant experience app", "BMS analytics"],
        sources=["linkedin", "costar"], score=86,
        qualification_notes="REIT with multi-building NYC portfolio. Regional VP exploring managed WiFi revenue.",
    ),
    _lead(
        company_name="Hines NYC",
        contact_name="Olivia Martinez", contact_title="Property Manager",
        email="olivia.martinez@hines.com", phone="(212) 201-3600",
        website="https://hines.com",
        address="499 Park Avenue, New York, NY 10022",
        building_type="Class A Office", sqft=320000, num_tenants=18,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=1981, floors=27, num_employees=45,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Pilot Fiber"],
        equipment={"hvac": "Carrier AquaEdge", "elevator": "Otis 2000E — 6 cabs", "security": "Brivo cloud access", "bms": "Honeywell Niagara", "network_infrastructure": "Cat5e legacy, needs upgrade"},
        building_summary="Boutique Class A on Park Ave. 27 floors, 320K sqft. Legacy Cat5e wiring limits tenant offerings. Full cable plant upgrade needed.",
        tech_signals=["cable plant upgrade RFP", "VOIP migration", "security camera refresh"],
        sources=["costar", "web_scraper"], score=73,
        qualification_notes="Legacy infrastructure = greenfield. Cable plant upgrade creates entry point.",
    ),
    _lead(
        company_name="WeWork NYC Portfolio",
        company_type="COWORKING",
        contact_name="Michael Torres", contact_title="Director of Technology",
        email="m.torres@wework.com", phone="(646) 491-5500",
        website="https://wework.com",
        address="115 W 18th Street, New York, NY 10011",
        building_type="Flex Space", sqft=85000, num_tenants=120,
        borough="Manhattan", neighborhood="Chelsea",
        year_built=1912, floors=12, num_employees=45,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Carrier VRF system", "elevator": "ThyssenKrupp — 2 cabs", "security": "Openpath mobile access", "bms": "Honeywell Niagara", "network_infrastructure": "Ubiquiti UniFi mesh, Cat6 throughout"},
        building_summary="Coworking in Chelsea. 12 floors, 85K sqft. 120+ member companies. High-density WiFi is the product. Tiered WiFi revenue opportunity.",
        current_it_provider="In-house", tech_signals=["WiFi 6E upgrade", "IoT occupancy sensors", "meeting room AV refresh"],
        sources=["web_scraper", "linkedin"], score=78,
        qualification_notes="Coworking operator — WiFi IS the product. Tiered connectivity revenue model pitch.",
    ),
    _lead(
        company_name="Industrious FiDi",
        company_type="COWORKING",
        contact_name="Lisa Wang", contact_title="Regional IT Manager",
        email="l.wang@industriousoffice.com", phone="(917) 310-4450",
        website="https://industriousoffice.com",
        address="222 Broadway, New York, NY 10038",
        building_type="Premium Flex Space", sqft=42000, num_tenants=60,
        borough="Manhattan", neighborhood="Financial District",
        year_built=1958, floors=6, num_employees=22,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Pilot Fiber"],
        equipment={"hvac": "Lennox rooftop units (aging)", "elevator": "Dover — 2 cabs", "security": "Brivo cloud access", "bms": "Legacy Honeywell (no cloud)", "network_infrastructure": "Cat5e legacy, Cisco Catalyst"},
        building_summary="Premium coworking in FiDi. 6 floors, 42K sqft. Legacy Cat5e limits premium tier pricing. No IT provider — greenfield.",
        tech_signals=["network refresh RFP", "VOIP migration", "cable plant upgrade needed"],
        sources=["marketplace", "web_scraper"], score=71,
        qualification_notes="Greenfield — no IT provider. Aging infra. Premium coworking needs premium WiFi.",
    ),
    _lead(
        company_name="Convene Flatiron",
        company_type="COWORKING",
        contact_name="Ryan Cho", contact_title="VP of Technology",
        email="r.cho@convene.com", phone="(212) 601-2500",
        website="https://convene.com",
        address="101 Park Avenue, New York, NY 10178",
        building_type="Meeting & Event Space", sqft=55000, num_tenants=0,
        borough="Manhattan", neighborhood="Flatiron",
        year_built=1950, floors=4, num_employees=35,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRF", "elevator": "Otis — 2 cabs", "security": "Openpath", "bms": "Distech Controls", "network_infrastructure": "Cat6a, Ruckus APs, dedicated fiber"},
        building_summary="Premium meeting and event space near Grand Central. AV-heavy environment. High-density WiFi critical for events.",
        current_it_provider="Managed internally", tech_signals=["AV infrastructure upgrade", "event WiFi capacity", "hybrid meeting tech"],
        sources=["linkedin", "web_scraper"], score=70,
        qualification_notes="Event-focused. High-density WiFi = revenue enabler. AV integration opportunity.",
    ),
    _lead(
        company_name="RXR Realty",
        company_type="MULTI_TENANT",
        contact_name="James Rivera", contact_title="CTO",
        email="j.rivera@rxr.com", phone="(212) 790-5800",
        website="https://rxr.com",
        address="75 Rockefeller Plaza, New York, NY 10019",
        building_type="Class A Office", sqft=630000, num_tenants=35,
        borough="Manhattan", neighborhood="Midtown",
        year_built=1947, floors=33, num_employees=85,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Zayo", "Lightpath"],
        equipment={"hvac": "York centrifugal (2021)", "elevator": "Schindler 7000 — 16 cabs", "security": "LenelS2 + Verkada", "bms": "Schneider EcoStruxure", "network_infrastructure": "MMF backbone, Cat6, Juniper EX"},
        building_summary="Rockefeller Center building. 33 floors, 630K sqft. CTO is PropTech-forward. RXR investing heavily in tenant experience tech.",
        current_it_provider="Converge Technology", tech_signals=["tenant experience app", "lobby digital signage", "parking IoT"],
        sources=["linkedin", "costar", "news"], score=85,
        qualification_notes="CTO is tech-forward. RXR PropTech fund. Multi-building portfolio opportunity.",
    ),
    _lead(
        company_name="Empire State Realty Trust",
        contact_name="Amanda Foster", contact_title="Director of Engineering",
        email="a.foster@esrtreit.com", phone="(212) 850-2600",
        website="https://esrtreit.com",
        address="111 W 33rd Street, New York, NY 10120",
        building_type="Class B+ Office", sqft=380000, num_tenants=42,
        borough="Manhattan", neighborhood="Midtown South",
        year_built=1928, floors=25, num_employees=55,
        building_isp="Crown Castle Fiber", available_isps=["Crown Castle Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Carrier 30XA air-cooled", "elevator": "Otis 2000E — 8 cabs", "security": "AMAG Symmetry", "bms": "Tridium Niagara 4", "network_infrastructure": "Cat6 risers, SMF backbone, Arista 7000"},
        building_summary="Class B+ near Penn Station. 25 floors, 380K sqft. ESRT portfolio includes Empire State Building. $500M modernization across portfolio.",
        current_it_provider="Presidio", tech_signals=["portfolio-wide BMS upgrade", "cybersecurity assessment", "emergency communication system"],
        sources=["nyc_opendata", "news", "costar"], score=88,
        qualification_notes="$500M modernization = massive IT opportunity. 10+ NYC buildings. Land-and-expand.",
    ),
    _lead(
        company_name="Mack Real Estate Group",
        company_type="MULTI_TENANT",
        contact_name="Robert Kim", contact_title="VP of Property Technology",
        email="r.kim@mackregroup.com", phone="(212) 355-5300",
        website="https://mackregroup.com",
        address="1 Manhattan West, New York, NY 10001",
        building_type="Class A Office", sqft=2100000, num_tenants=22,
        borough="Manhattan", neighborhood="Hudson Yards",
        year_built=2019, floors=67, num_employees=250,
        building_isp="Zayo", available_isps=["Zayo", "Verizon Fios", "Pilot Fiber", "Crown Castle Fiber", "Cogent"],
        equipment={"hvac": "Trane CenTraVac centrifugal", "elevator": "ThyssenKrupp TWIN — 28 cabs", "security": "Genetec + thermal cameras", "bms": "Siemens Desigo CC with AI", "network_infrastructure": "SMF backbone, Cat6a, Cisco Nexus 9000"},
        building_summary="Flagship at Manhattan West. 67 floors, 2.1M sqft. Full smart building. VP of PropTech consolidating from 4 MSPs to 1.",
        current_it_provider="Accenture + multiple MSPs", tech_signals=["consolidating MSPs", "digital twin v2", "tenant portal", "ESG platform"],
        sources=["linkedin", "costar", "news", "nyc_opendata"], score=97,
        qualification_notes="Highest-value target. Consolidating 4 MSPs to 1. Budget: $2M+/year.",
    ),
    _lead(
        company_name="Rudin Management",
        contact_name="Samantha Greene", contact_title="Head of Innovation",
        email="s.greene@rudin.com", phone="(212) 407-2400",
        website="https://rudin.com",
        address="345 Park Avenue, New York, NY 10154",
        building_type="Class A Office", sqft=800000, num_tenants=30,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=1969, floors=44, num_employees=120,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Pilot Fiber"],
        equipment={"hvac": "Trane CenTraVac", "elevator": "Otis — 18 cabs", "security": "Kastle Systems", "bms": "Johnson Controls (custom)", "network_infrastructure": "Cat6, MMF backbone, Cisco Meraki"},
        building_summary="Rudin Management operates Nantum OS smart building platform. 44 floors, 800K sqft. Innovation-forward family-owned CRE firm.",
        current_it_provider="In-house Nantum OS", tech_signals=["Nantum OS expansion", "tenant connectivity program", "smart HVAC"],
        sources=["linkedin", "news"], score=84,
        qualification_notes="Built their own PropTech platform (Nantum OS). Infrastructure partner opportunity.",
    ),
    _lead(
        company_name="GFP Real Estate",
        company_type="MULTI_TENANT",
        contact_name="Mark Stevens", contact_title="Building Manager",
        email="m.stevens@gfprealestate.com", phone="(212) 609-8000",
        website="https://gfprealestate.com",
        address="515 Madison Avenue, New York, NY 10022",
        building_type="Class B Office", sqft=180000, num_tenants=25,
        borough="Manhattan", neighborhood="Midtown East",
        year_built=1952, floors=18, num_employees=30,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Lennox rooftop (aging)", "elevator": "Dover — 3 cabs", "security": "Brivo cloud", "bms": "None — manual", "network_infrastructure": "Cat5e legacy, consumer-grade APs"},
        building_summary="Mid-size Class B on Madison Ave. 18 floors, 180K sqft. Aging infrastructure. No BMS. Manual operations. Full modernization opportunity.",
        tech_signals=["full infrastructure audit needed", "tenant complaints about WiFi", "security upgrade"],
        sources=["marketplace", "web_scraper"], score=68,
        qualification_notes="Legacy building screaming for upgrade. Tenant WiFi complaints = sales leverage.",
    ),
    _lead(
        company_name="SoHo Properties",
        company_type="MULTI_TENANT",
        contact_name="Laura Chen", contact_title="Property Director",
        email="l.chen@sohoproperties.com", phone="(212) 625-3200",
        website="https://sohoproperties.com",
        address="568 Broadway, New York, NY 10012",
        building_type="Loft Office", sqft=120000, num_tenants=35,
        borough="Manhattan", neighborhood="SoHo",
        year_built=1896, floors=8, num_employees=15,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Mitsubishi mini-splits", "elevator": "Hydraulic — 1 cab", "security": "Kisi mobile access", "bms": "None", "network_infrastructure": "Cat5e, Ubiquiti UniFi APs"},
        building_summary="Historic SoHo loft building. 8 floors, 120K sqft. 35 small tenants (design, media, tech). High WiFi density needed. Legacy Cat5e wiring.",
        tech_signals=["WiFi upgrade needed", "Cat6 rewiring", "shared conference room AV"],
        sources=["web_scraper", "marketplace"], score=65,
        qualification_notes="35 tenants in creative loft — high density WiFi opportunity. Cat5e → Cat6a upgrade needed.",
    ),
    _lead(
        company_name="Tribeca Associates",
        company_type="MULTI_TENANT",
        contact_name="Nick Andersen", contact_title="Operations VP",
        email="n.andersen@tribecaassociates.com", phone="(212) 334-0009",
        website="https://tribecaassociates.com",
        address="70 Hudson Street, New York, NY 10013",
        building_type="Converted Warehouse", sqft=250000, num_tenants=20,
        borough="Manhattan", neighborhood="Tribeca",
        year_built=1910, floors=10, num_employees=25,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios"],
        equipment={"hvac": "VRF system (2020 install)", "elevator": "ThyssenKrupp — 3 cabs", "security": "Openpath mobile", "bms": "Distech Controls", "network_infrastructure": "Cat6 horizontal, MMF backbone, Meraki APs"},
        building_summary="Converted warehouse in Tribeca. 10 floors, 250K sqft. Mix of media, tech, and financial tenants. Modern MEP but network needs managed services layer.",
        tech_signals=["managed WiFi interest", "tenant portal", "package management system"],
        sources=["costar", "web_scraper"], score=72,
        qualification_notes="Modern MEP, needs managed services layer. Good fit for Revenue-as-a-Service pitch.",
    ),
    _lead(
        company_name="Fifth Wall Portfolio — Latch",
        company_type="OTHER",
        contact_name="Emily Park", contact_title="Director of Building Partnerships",
        email="emily.park@latch.com", phone="(917) 555-0142",
        website="https://latch.com",
        address="508 W 26th Street, New York, NY 10001",
        building_type="Smart Access Office", sqft=25000, num_tenants=0,
        borough="Manhattan", neighborhood="Chelsea",
        year_built=2015, floors=5, num_employees=80,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRF", "elevator": "None", "security": "Latch hardware + cloud", "bms": "Latch OS", "network_infrastructure": "Cat6a, Ruckus WiFi 6E"},
        building_summary="Fifth Wall portfolio company. Smart access hardware/software for buildings. Partnership opportunity — they install access control, we install the network it runs on.",
        tech_signals=["preferred installer program", "network infrastructure partnerships", "building IoT ecosystem"],
        sources=["linkedin", "news"], score=80,
        qualification_notes="Fifth Wall PropTech portfolio. Partnership model — preferred infrastructure installer for their access control deployments.",
    ),
]

# =============================================================================
# BROOKLYN — 10 leads
# =============================================================================
BROOKLYN = [
    _lead(
        company_name="Two Trees Management",
        contact_name="Carlos Mendez", contact_title="Director of Technology",
        email="c.mendez@twotreesny.com", phone="(718) 222-2500",
        website="https://twotreesny.com",
        address="45 Main Street, Brooklyn, NY 11201",
        building_type="Mixed-Use", sqft=1200000, num_tenants=60,
        borough="Brooklyn", neighborhood="DUMBO",
        year_built=1910, floors=12, num_employees=150,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "VRF systems throughout", "elevator": "Schindler — 6 cabs", "security": "Openpath + Verkada", "bms": "Siemens Desigo", "network_infrastructure": "SMF backbone, Cat6a, Aruba APs"},
        building_summary="Two Trees owns most of DUMBO. 1.2M sqft across multiple buildings. 60+ tenants including tech companies. Campus-wide WiFi opportunity.",
        current_it_provider="Multiple vendors", tech_signals=["campus WiFi consolidation", "tenant portal", "outdoor WiFi for DUMBO streets"],
        sources=["costar", "news", "linkedin"], score=89,
        qualification_notes="Two Trees owns DUMBO. Campus-wide WiFi-as-a-service across entire neighborhood. Huge opportunity.",
    ),
    _lead(
        company_name="Industry City",
        company_type="MULTI_TENANT",
        contact_name="Jason Wu", contact_title="VP of Operations",
        email="j.wu@industrycity.com", phone="(718) 965-6450",
        website="https://industrycity.com",
        address="220 36th Street, Brooklyn, NY 11232",
        building_type="Industrial/Creative Campus", sqft=6000000, num_tenants=500,
        borough="Brooklyn", neighborhood="Sunset Park",
        year_built=1895, floors=6, num_employees=400,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Pilot Fiber"],
        equipment={"hvac": "Mixed — industrial units", "elevator": "Freight — 8 cabs", "security": "Genetec + turnstiles", "bms": "Honeywell Niagara", "network_infrastructure": "Legacy copper + partial fiber, Ubiquiti mesh"},
        building_summary="Massive 6M sqft industrial/creative campus. 500+ tenants. 16 buildings. Aging network needs full overhaul. WiFi-as-a-service potential: 500 tenants × $50/mo = $25K/mo.",
        tech_signals=["campus-wide network RFP", "fiber backbone needed", "tenant WiFi demand"],
        sources=["news", "web_scraper", "costar"], score=92,
        qualification_notes="6M sqft, 500 tenants. WiFi revenue: $300K/year potential. Massive infrastructure project.",
    ),
    _lead(
        company_name="Forest City Realty — MetroTech",
        company_type="MULTI_TENANT",
        contact_name="Patricia Brown", contact_title="Property Manager",
        email="p.brown@forestcity.com", phone="(718) 923-8400",
        website="https://forestcity.com",
        address="1 MetroTech Center, Brooklyn, NY 11201",
        building_type="Class A Office", sqft=550000, num_tenants=25,
        borough="Brooklyn", neighborhood="Downtown Brooklyn",
        year_built=1992, floors=18, num_employees=80,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Lightpath"],
        equipment={"hvac": "Trane centrifugal", "elevator": "Otis — 12 cabs", "security": "Kastle Systems", "bms": "Johnson Controls", "network_infrastructure": "Cat5e risers (original 1992), Cisco Catalyst"},
        building_summary="MetroTech Center campus. 18 floors, 550K sqft. Major tenants include city agencies and tech firms. Original 1992 cabling — overdue for upgrade.",
        tech_signals=["cable plant refresh", "tenant WiFi complaints", "lobby modernization"],
        sources=["nyc_opendata", "costar"], score=74,
        qualification_notes="Original 1992 Cat5e wiring. Upgrade needed. 25 tenants for WiFi revenue.",
    ),
    _lead(
        company_name="Green Desk DUMBO",
        company_type="COWORKING",
        contact_name="Maya Rodriguez", contact_title="Operations Manager",
        email="maya@greendesk.com", phone="(718) 230-3180",
        website="https://greendesk.com",
        address="155 Water Street, Brooklyn, NY 11201",
        building_type="Converted Warehouse", sqft=28000, num_tenants=40,
        borough="Brooklyn", neighborhood="DUMBO",
        year_built=1905, floors=4, num_employees=8,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Optimum Business"],
        equipment={"hvac": "Mitsubishi mini-splits", "elevator": "Freight — 1 cab", "security": "Kisi cloud access", "bms": "None — manual", "network_infrastructure": "Cat5e, Ubiquiti UniFi APs"},
        building_summary="Eco-friendly coworking in DUMBO warehouse. 4 floors, 28K sqft. Green-certified. No current IT provider — complete greenfield.",
        tech_signals=["managed WiFi needed", "print management", "backup solution"],
        sources=["web_scraper", "marketplace"], score=62,
        qualification_notes="Greenfield — no IT provider. Small but growing. Budget-conscious.",
    ),
    _lead(
        company_name="The Yard — Williamsburg",
        company_type="COWORKING",
        contact_name="Alex Thompson", contact_title="Director of Technology",
        email="alex@theyard.nyc", phone="(718) 218-6073",
        website="https://theyard.nyc",
        address="33 Nassau Avenue, Brooklyn, NY 11222",
        building_type="Flex Space", sqft=35000, num_tenants=80,
        borough="Brooklyn", neighborhood="Williamsburg",
        year_built=1920, floors=5, num_employees=12,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Pilot Fiber"],
        equipment={"hvac": "Split systems", "elevator": "None", "security": "Brivo", "bms": "None", "network_infrastructure": "Cat6, Meraki APs"},
        building_summary="Trendy Williamsburg coworking. 5 floors, 35K sqft. 80 member companies. Needs reliable high-density WiFi for creative tenants.",
        tech_signals=["WiFi capacity issues", "AV for event space", "VPN support for enterprise members"],
        sources=["web_scraper", "linkedin"], score=66,
        qualification_notes="80 members. WiFi tiering opportunity. AV for events.",
    ),
    _lead(
        company_name="Spaces Brooklyn Heights (IWG)",
        company_type="COWORKING",
        contact_name="Jordan Davis", contact_title="Center Manager",
        email="j.davis@spaces.com", phone="(718) 858-7700",
        website="https://spacesworks.com",
        address="177 Montague Street, Brooklyn, NY 11201",
        building_type="Premium Flex Space", sqft=22000, num_tenants=45,
        borough="Brooklyn", neighborhood="Brooklyn Heights",
        year_built=1965, floors=3, num_employees=8,
        building_isp="Optimum Business", available_isps=["Optimum Business", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Carrier rooftop units", "elevator": "1 cab", "security": "HID iClass", "bms": "None", "network_infrastructure": "Cat5e, consumer-grade router"},
        building_summary="IWG Spaces location in Brooklyn Heights. 3 floors, 22K sqft. Legacy networking. Enterprise members complaining about WiFi performance.",
        tech_signals=["WiFi upgrade urgent", "member complaints", "enterprise tier demand"],
        sources=["marketplace", "web_scraper"], score=64,
        qualification_notes="Enterprise member complaints about WiFi. Urgent upgrade. Easy win.",
    ),
    _lead(
        company_name="Brooklyn Navy Yard Development Corp",
        company_type="MULTI_TENANT",
        contact_name="Ahmed Hassan", contact_title="Director of Infrastructure",
        email="a.hassan@brooklynnavyyard.org", phone="(718) 907-5900",
        website="https://brooklynnavyyard.org",
        address="63 Flushing Avenue, Brooklyn, NY 11205",
        building_type="Industrial/Tech Campus", sqft=4500000, num_tenants=450,
        borough="Brooklyn", neighborhood="Navy Yard",
        year_built=1941, floors=6, num_employees=300,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Pilot Fiber", "Crown Castle Fiber"],
        equipment={"hvac": "Mixed industrial/modern", "elevator": "Freight — 12 cabs", "security": "Genetec Security Center", "bms": "Johnson Controls (partial)", "network_infrastructure": "Partial fiber backbone, mostly legacy copper"},
        building_summary="4.5M sqft industrial campus. 450+ tenants including Steiner Studios, WeWork Labs. Major expansion underway. Campus-wide fiber needed.",
        tech_signals=["campus fiber backbone RFP", "new building construction", "smart campus initiative"],
        sources=["news", "nyc_opendata", "costar"], score=90,
        qualification_notes="4.5M sqft campus, 450 tenants. Major expansion. Campus fiber RFP active. Huge multi-year project.",
    ),
    _lead(
        company_name="Rabsky Group",
        company_type="MULTI_TENANT",
        contact_name="David Schwartz", contact_title="Property Manager",
        email="d.schwartz@rabsky.com", phone="(718) 222-8800",
        website="https://rabsky.com",
        address="215 Moore Street, Brooklyn, NY 11206",
        building_type="Mixed-Use Development", sqft=400000, num_tenants=30,
        borough="Brooklyn", neighborhood="East Williamsburg",
        year_built=2023, floors=12, num_employees=20,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRF", "elevator": "Kone — 4 cabs", "security": "HID Origo mobile", "bms": "Distech Controls", "network_infrastructure": "Cat6a, fiber risers, Aruba APs"},
        building_summary="New mixed-use development. 12 floors, 400K sqft. Modern infrastructure. Looking for managed WiFi as tenant amenity.",
        tech_signals=["tenant WiFi amenity", "package lockers", "building app"],
        sources=["costar", "web_scraper"], score=75,
        qualification_notes="New building, modern infra. Wants managed WiFi as premium amenity.",
    ),
    _lead(
        company_name="Dermot Company — Park Slope",
        company_type="MULTI_TENANT",
        contact_name="Christine Miller", contact_title="VP of Asset Management",
        email="c.miller@dermot.com", phone="(212) 789-3000",
        website="https://dermot.com",
        address="461 Dean Street, Brooklyn, NY 11217",
        building_type="Mixed-Use Commercial", sqft=180000, num_tenants=15,
        borough="Brooklyn", neighborhood="Park Slope",
        year_built=2019, floors=8, num_employees=20,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Optimum Business"],
        equipment={"hvac": "VRF system", "elevator": "Otis — 2 cabs", "security": "Openpath", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6, Meraki APs"},
        building_summary="Modern mixed-use in Park Slope. 8 floors, 180K sqft. Commercial ground floor + office. Managed WiFi as building amenity.",
        tech_signals=["building-wide WiFi", "tenant experience platform", "smart lobby"],
        sources=["costar", "marketplace"], score=67,
        qualification_notes="Newer building, amenity-focused. WiFi-as-a-service fits their model.",
    ),
    _lead(
        company_name="RockRose Development — Downtown BK",
        company_type="MULTI_TENANT",
        contact_name="Steven Park", contact_title="Director of Operations",
        email="s.park@rockrose.com", phone="(718) 875-6200",
        website="https://rockrose.com",
        address="388 Bridge Street, Brooklyn, NY 11201",
        building_type="Class A Office", sqft=300000, num_tenants=22,
        borough="Brooklyn", neighborhood="Downtown Brooklyn",
        year_built=2018, floors=20, num_employees=35,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRV IV", "elevator": "ThyssenKrupp — 6 cabs", "security": "HID mobile", "bms": "Siemens Desigo", "network_infrastructure": "Cat6a, SMF backbone, Cisco Meraki"},
        building_summary="Modern Class A in Downtown Brooklyn. 20 floors, 300K sqft. RockRose portfolio building. Well-maintained infrastructure ready for managed services.",
        tech_signals=["managed WiFi interest", "tenant app", "DAS for mobile coverage"],
        sources=["costar", "linkedin"], score=76,
        qualification_notes="Modern building, ready for managed WiFi layer. 22 tenants for revenue model.",
    ),
]

# =============================================================================
# QUEENS — 10 leads
# =============================================================================
QUEENS = [
    _lead(
        company_name="TF Cornerstone — LIC",
        company_type="MULTI_TENANT",
        contact_name="Michael Chang", contact_title="Director of Property Technology",
        email="m.chang@tfcornerstone.com", phone="(718) 786-5000",
        website="https://tfcornerstone.com",
        address="46-01 5th Street, Long Island City, NY 11101",
        building_type="Class A Office/Mixed-Use", sqft=800000, num_tenants=40,
        borough="Queens", neighborhood="Long Island City",
        year_built=2019, floors=35, num_employees=100,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Pilot Fiber"],
        equipment={"hvac": "Daikin VRV IV", "elevator": "Kone — 8 cabs", "security": "HID Origo + Verkada", "bms": "Siemens Desigo", "network_infrastructure": "Cat6a, SMF backbone, Aruba CX switches"},
        building_summary="Major LIC development. 35 floors, 800K sqft. Modern smart building. TF Cornerstone exploring WiFi-as-a-service across LIC portfolio.",
        tech_signals=["portfolio WiFi strategy", "smart building analytics", "tenant portal"],
        sources=["costar", "news", "linkedin"], score=85,
        qualification_notes="Modern LIC building. Multi-building portfolio. WiFi revenue model interest.",
    ),
    _lead(
        company_name="Plaxall Inc",
        company_type="MULTI_TENANT",
        contact_name="Grace Kim", contact_title="Operations Manager",
        email="g.kim@plaxall.com", phone="(718) 784-2200",
        website="https://plaxall.com",
        address="5-25 46th Avenue, Long Island City, NY 11101",
        building_type="Industrial/Creative", sqft=500000, num_tenants=60,
        borough="Queens", neighborhood="Long Island City",
        year_built=1940, floors=5, num_employees=35,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Mixed industrial", "elevator": "Freight — 3 cabs", "security": "Basic card access", "bms": "None", "network_infrastructure": "Partial Cat5e, basic switches"},
        building_summary="Industrial campus transitioning to creative/tech tenants. 5 floors, 500K sqft. 60 tenants. Legacy infrastructure needs complete overhaul.",
        tech_signals=["campus WiFi needed", "fiber backbone", "security upgrade"],
        sources=["web_scraper", "nyc_opendata"], score=72,
        qualification_notes="60 tenants transitioning to tech. Infrastructure upgrade needed. WiFi revenue opportunity.",
    ),
    _lead(
        company_name="Kaufman Astoria Studios",
        company_type="OTHER",
        contact_name="Tony Vasquez", contact_title="VP of Facilities",
        email="t.vasquez@kaufmanastoria.com", phone="(718) 392-5600",
        website="https://kaufmanastoria.com",
        address="34-12 36th Street, Astoria, NY 11106",
        building_type="Production Studio Campus", sqft=300000, num_tenants=15,
        borough="Queens", neighborhood="Astoria",
        year_built=1920, floors=4, num_employees=120,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Lightpath"],
        equipment={"hvac": "Industrial HVAC + sound-dampened", "elevator": "Freight — 2 cabs", "security": "Genetec Security Center", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6 in offices, fiber to stages, Cisco switches"},
        building_summary="Historic production studio campus. 4 floors, 300K sqft. Production stages need high-bandwidth, low-latency connectivity. Growing demand for cloud production.",
        tech_signals=["cloud production infrastructure", "10G fiber to stages", "WiFi for production"],
        sources=["news", "web_scraper"], score=76,
        qualification_notes="Specialized production needs. High-bandwidth opportunity. Cloud production trend.",
    ),
    _lead(
        company_name="Flushing Commons LLC",
        company_type="MULTI_TENANT",
        contact_name="Henry Liu", contact_title="General Manager",
        email="h.liu@flushingcommons.com", phone="(718) 886-3000",
        website="https://flushingcommons.com",
        address="135-35 38th Avenue, Flushing, NY 11354",
        building_type="Mixed-Use Development", sqft=650000, num_tenants=50,
        borough="Queens", neighborhood="Flushing",
        year_built=2022, floors=15, num_employees=40,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRF", "elevator": "Otis Gen3 — 6 cabs", "security": "HID mobile", "bms": "Distech Controls", "network_infrastructure": "Cat6a, SMF backbone, Ruckus APs"},
        building_summary="New mixed-use development in downtown Flushing. 15 floors, 650K sqft. 50 commercial tenants. Modern infrastructure. Managed WiFi as amenity.",
        tech_signals=["tenant WiFi amenity", "digital signage", "visitor management"],
        sources=["costar", "nyc_opendata"], score=74,
        qualification_notes="New development with 50 commercial tenants. Ready for managed WiFi.",
    ),
    _lead(
        company_name="Premier Equities — Jamaica",
        company_type="MULTI_TENANT",
        contact_name="Robert Williams", contact_title="Building Manager",
        email="r.williams@premierequities.com", phone="(718) 523-4900",
        website="https://premierequities.com",
        address="89-14 Parsons Boulevard, Jamaica, NY 11432",
        building_type="Class B Office", sqft=120000, num_tenants=20,
        borough="Queens", neighborhood="Jamaica",
        year_built=1975, floors=8, num_employees=15,
        building_isp="Optimum Business", available_isps=["Optimum Business", "Verizon Fios"],
        equipment={"hvac": "Carrier rooftop (aging)", "elevator": "Dover — 2 cabs", "security": "Legacy card readers", "bms": "None", "network_infrastructure": "Cat5e legacy, basic consumer router"},
        building_summary="Class B office near Jamaica transit hub. 8 floors, 120K sqft. Aging infrastructure. Gateway to JFK Airport area businesses.",
        tech_signals=["complete infrastructure refresh needed", "security upgrade", "tenant internet"],
        sources=["nyc_opendata", "marketplace"], score=58,
        qualification_notes="Legacy building needs everything. Lower budget but greenfield opportunity.",
    ),
    _lead(
        company_name="JACX Development — LIC",
        company_type="CRE_OPERATOR",
        contact_name="Sarah Nakamura", contact_title="Director of Operations",
        email="s.nakamura@jacx.com", phone="(718) 706-7200",
        website="https://jacx.com",
        address="28-07 Jackson Avenue, Long Island City, NY 11101",
        building_type="Class A Mixed-Use", sqft=1200000, num_tenants=30,
        borough="Queens", neighborhood="Long Island City",
        year_built=2020, floors=26, num_employees=60,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Trane CenTraVac", "elevator": "Kone — 10 cabs", "security": "Evolv Express + HID", "bms": "Johnson Controls OpenBlue", "network_infrastructure": "SMF backbone, Cat6a, Aruba Wi-Fi 6"},
        building_summary="Modern Class A development in LIC. 26 floors, 1.2M sqft. Full smart building. Exploring managed connectivity as NOI enhancer.",
        tech_signals=["WiFi-as-a-service interest", "tenant app", "parking IoT"],
        sources=["costar", "linkedin", "news"], score=83,
        qualification_notes="New smart building. Director exploring WiFi revenue model. 30 tenants.",
    ),
    _lead(
        company_name="Atlas Capital Group — LIC",
        company_type="CRE_OPERATOR",
        contact_name="Peter Gomez", contact_title="Asset Manager",
        email="p.gomez@atlascapitalgroup.com", phone="(718) 937-2100",
        website="https://atlascapitalgroup.com",
        address="44-28 Purves Street, Long Island City, NY 11101",
        building_type="Mixed-Use", sqft=350000, num_tenants=25,
        borough="Queens", neighborhood="Long Island City",
        year_built=2021, floors=18, num_employees=20,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "VRF system", "elevator": "Otis Gen3 — 4 cabs", "security": "Openpath", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6a, Meraki APs"},
        building_summary="Newer LIC mixed-use. 18 floors, 350K sqft. Modern infrastructure. Seeking managed WiFi as competitive amenity.",
        tech_signals=["managed WiFi", "building app", "package management"],
        sources=["costar", "marketplace"], score=70,
        qualification_notes="Modern building looking for managed WiFi to compete in LIC market.",
    ),
    _lead(
        company_name="George Comfort & Sons — Rego Park",
        company_type="MULTI_TENANT",
        contact_name="Linda Torres", contact_title="Property Manager",
        email="l.torres@georgecomfort.com", phone="(718) 459-3500",
        website="https://georgecomfort.com",
        address="97-77 Queens Boulevard, Rego Park, NY 11374",
        building_type="Class B Office", sqft=200000, num_tenants=18,
        borough="Queens", neighborhood="Rego Park",
        year_built=1968, floors=12, num_employees=25,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Carrier rooftop units", "elevator": "Otis 2000E — 4 cabs", "security": "LenelS2", "bms": "Legacy Honeywell", "network_infrastructure": "Cat5e, aging Cisco switches"},
        building_summary="Class B office on Queens Blvd. 12 floors, 200K sqft. Aging infrastructure. Tenants bringing own internet = missed revenue opportunity.",
        tech_signals=["tenant internet consolidation", "cable plant upgrade", "security refresh"],
        sources=["nyc_opendata", "web_scraper"], score=65,
        qualification_notes="Tenants bring own ISP — revenue leakage. Building-provided WiFi pitch.",
    ),
    _lead(
        company_name="L+M Development — LIC",
        company_type="CRE_OPERATOR",
        contact_name="Daniel Okafor", contact_title="VP of Construction Technology",
        email="d.okafor@lmdevpartners.com", phone="(718) 706-3500",
        website="https://lmdevpartners.com",
        address="23-10 Queens Plaza South, Long Island City, NY 11101",
        building_type="Class A Mixed-Use", sqft=450000, num_tenants=20,
        borough="Queens", neighborhood="Long Island City",
        year_built=2023, floors=22, num_employees=30,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Pilot Fiber", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRV IV", "elevator": "Kone — 6 cabs", "security": "HID Origo", "bms": "Distech Controls", "network_infrastructure": "Cat6a, fiber risers, Ruckus Wi-Fi 6E"},
        building_summary="Brand new Class A in LIC. 22 floors, 450K sqft. Modern infrastructure. VP interested in WiFi revenue model from day one.",
        tech_signals=["WiFi revenue from opening", "smart building features", "tenant app"],
        sources=["costar", "linkedin"], score=79,
        qualification_notes="Brand new building. Wants WiFi-as-a-service from day one. Clean infrastructure.",
    ),
    _lead(
        company_name="Vorea Group — LIC Waterfront",
        company_type="CRE_OPERATOR",
        contact_name="Chris Anderson", contact_title="Property Director",
        email="c.anderson@voreagroup.com", phone="(718) 786-9100",
        website="https://voreagroup.com",
        address="4-74 48th Avenue, Long Island City, NY 11109",
        building_type="Mixed-Use Waterfront", sqft=280000, num_tenants=15,
        borough="Queens", neighborhood="Long Island City",
        year_built=2020, floors=15, num_employees=18,
        building_isp="Pilot Fiber", available_isps=["Pilot Fiber", "Verizon Fios"],
        equipment={"hvac": "VRF system", "elevator": "Otis — 4 cabs", "security": "Openpath mobile", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6a, Meraki APs, fiber backbone"},
        building_summary="LIC waterfront mixed-use. 15 floors, 280K sqft. Modern infrastructure. Wants to offer premium connectivity as amenity.",
        tech_signals=["premium WiFi tiers", "rooftop WiFi for events", "tenant experience"],
        sources=["costar", "web_scraper"], score=68,
        qualification_notes="Modern waterfront building. Premium WiFi tier opportunity.",
    ),
]

# =============================================================================
# BRONX — 10 leads
# =============================================================================
BRONX = [
    _lead(
        company_name="Somerset Partners — Mott Haven",
        company_type="CRE_OPERATOR",
        contact_name="Ricardo Santos", contact_title="Development Director",
        email="r.santos@somersetpartners.com", phone="(718) 585-3500",
        website="https://somersetpartners.com",
        address="101 Lincoln Avenue, Bronx, NY 10454",
        building_type="Mixed-Use Development", sqft=500000, num_tenants=30,
        borough="Bronx", neighborhood="Mott Haven",
        year_built=2022, floors=15, num_employees=25,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRF", "elevator": "Otis Gen3 — 4 cabs", "security": "HID mobile access", "bms": "Distech Controls", "network_infrastructure": "Cat6a, fiber risers, Ruckus APs"},
        building_summary="New Mott Haven mixed-use development. 15 floors, 500K sqft. Part of South Bronx renaissance. Modern infrastructure ready for managed WiFi.",
        tech_signals=["managed WiFi amenity", "tenant app", "smart lobby"],
        sources=["costar", "news"], score=77,
        qualification_notes="New Mott Haven development. South Bronx growth area. Modern infra.",
    ),
    _lead(
        company_name="Simone Development — Pelham Bay",
        company_type="MULTI_TENANT",
        contact_name="Frank Simone Jr", contact_title="VP of Operations",
        email="f.simone@simonedevelopment.com", phone="(718) 518-8500",
        website="https://simonedevelopment.com",
        address="1250 Waters Place, Bronx, NY 10461",
        building_type="Commercial Office Park", sqft=1500000, num_tenants=80,
        borough="Bronx", neighborhood="Pelham Bay",
        year_built=2005, floors=8, num_employees=60,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Lightpath"],
        equipment={"hvac": "Trane rooftop units", "elevator": "Schindler — 6 cabs", "security": "Genetec", "bms": "Johnson Controls", "network_infrastructure": "Cat6, MMF backbone, Cisco Catalyst"},
        building_summary="Hutchinson Metro Center — Bronx's largest commercial campus. 1.5M sqft, 80+ tenants. Office park needs campus-wide WiFi and upgraded networking.",
        current_it_provider="Multiple vendors", tech_signals=["campus WiFi consolidation", "fiber upgrade", "DAS for mobile"],
        sources=["costar", "nyc_opendata"], score=82,
        qualification_notes="Largest Bronx commercial campus. 80 tenants for WiFi revenue. $250K/year potential.",
    ),
    _lead(
        company_name="Innovo Property Group — Port Morris",
        company_type="CRE_OPERATOR",
        contact_name="Maria Gonzalez", contact_title="Asset Manager",
        email="m.gonzalez@innovopg.com", phone="(718) 402-1500",
        website="https://innovopg.com",
        address="980 E 149th Street, Bronx, NY 10455",
        building_type="Industrial/Last-Mile Logistics", sqft=800000, num_tenants=15,
        borough="Bronx", neighborhood="Port Morris",
        year_built=2021, floors=5, num_employees=30,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Industrial RTU", "elevator": "Freight — 4 cabs", "security": "Genetec + License Plate Recognition", "bms": "Johnson Controls", "network_infrastructure": "Cat6, industrial WiFi, basic switches"},
        building_summary="Modern last-mile logistics hub in Port Morris. 5 floors, 800K sqft. IoT-heavy for logistics operations. Growing need for managed network.",
        tech_signals=["IoT logistics sensors", "warehouse WiFi", "fleet management connectivity"],
        sources=["costar", "news"], score=70,
        qualification_notes="Logistics hub needs industrial WiFi and IoT connectivity. Growing sector.",
    ),
    _lead(
        company_name="BRP Companies — Mott Haven",
        company_type="MULTI_TENANT",
        contact_name="Andre Johnson", contact_title="Property Manager",
        email="a.johnson@brpcompanies.com", phone="(718) 993-5000",
        website="https://brpcompanies.com",
        address="425 Grand Concourse, Bronx, NY 10451",
        building_type="Mixed-Use", sqft=300000, num_tenants=20,
        borough="Bronx", neighborhood="Mott Haven",
        year_built=2020, floors=12, num_employees=15,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "VRF system", "elevator": "Otis — 3 cabs", "security": "Openpath", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6a, Meraki APs"},
        building_summary="New mixed-use on Grand Concourse. 12 floors, 300K sqft. Commercial ground floor + office. Part of Mott Haven growth.",
        tech_signals=["building WiFi", "tenant portal", "smart lighting"],
        sources=["costar", "marketplace"], score=68,
        qualification_notes="New building in growing Mott Haven area. Ready for managed services.",
    ),
    _lead(
        company_name="GreenHouse Group — South Bronx",
        company_type="COWORKING",
        contact_name="Tanya Williams", contact_title="Center Director",
        email="tanya@greenhousegroup.com", phone="(718) 292-6400",
        website="https://greenhousegroup.com",
        address="888 E 163rd Street, Bronx, NY 10459",
        building_type="Coworking/Incubator", sqft=15000, num_tenants=30,
        borough="Bronx", neighborhood="Foxhurst",
        year_built=2018, floors=2, num_employees=6,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Split systems", "elevator": "None", "security": "Kisi cloud", "bms": "None", "network_infrastructure": "Cat5e, consumer-grade APs"},
        building_summary="Community coworking/incubator in South Bronx. 2 floors, 15K sqft. 30 member businesses. Basic infrastructure. Budget-conscious.",
        tech_signals=["WiFi upgrade", "video conferencing", "print management"],
        sources=["web_scraper", "marketplace"], score=52,
        qualification_notes="Small community coworking. Lower budget but steady. Social impact angle.",
    ),
    _lead(
        company_name="Galil Management — Grand Concourse",
        company_type="MULTI_TENANT",
        contact_name="Isaac Levy", contact_title="Building Manager",
        email="i.levy@galilmgmt.com", phone="(718) 731-8000",
        website="https://galilmgmt.com",
        address="1188 Grand Concourse, Bronx, NY 10456",
        building_type="Class B Office", sqft=150000, num_tenants=22,
        borough="Bronx", neighborhood="Grand Concourse",
        year_built=1960, floors=10, num_employees=12,
        building_isp="Optimum Business", available_isps=["Optimum Business", "Verizon Fios"],
        equipment={"hvac": "Window units + central heat", "elevator": "Otis — 2 cabs", "security": "Buzzer system", "bms": "None", "network_infrastructure": "Cat3 telephone wiring, no data infrastructure"},
        building_summary="Classic Grand Concourse office building. 10 floors, 150K sqft. Zero data infrastructure — Cat3 telephone wiring only. Complete network build needed.",
        tech_signals=["complete network build", "tenant internet service", "basic security upgrade"],
        sources=["nyc_opendata", "marketplace"], score=55,
        qualification_notes="Zero existing data infra. Complete build = maximum control and revenue capture.",
    ),
    _lead(
        company_name="Fordham Properties LLC",
        company_type="MULTI_TENANT",
        contact_name="Carmen Rivera", contact_title="Property Manager",
        email="c.rivera@fordhamproperties.com", phone="(718) 933-5000",
        website="https://fordhamproperties.com",
        address="2500 Grand Concourse, Bronx, NY 10458",
        building_type="Class B Office", sqft=180000, num_tenants=25,
        borough="Bronx", neighborhood="Fordham",
        year_built=1972, floors=12, num_employees=18,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Optimum Business"],
        equipment={"hvac": "Carrier rooftop", "elevator": "Dover — 3 cabs", "security": "Card reader", "bms": "None", "network_infrastructure": "Cat5e partial, basic switches"},
        building_summary="Office building near Fordham University. 12 floors, 180K sqft. Legacy wiring. Near university = potential for student/faculty tenant connectivity.",
        tech_signals=["cable plant upgrade", "WiFi for tenants", "security cameras"],
        sources=["nyc_opendata", "web_scraper"], score=60,
        qualification_notes="Near Fordham University. Tenant WiFi demand. Legacy infra.",
    ),
    _lead(
        company_name="Turnbridge Equities — South Bronx",
        company_type="CRE_OPERATOR",
        contact_name="Jason Park", contact_title="Development Manager",
        email="j.park@turnbridgeequities.com", phone="(718) 402-8800",
        website="https://turnbridgeequities.com",
        address="320 Walton Avenue, Bronx, NY 10451",
        building_type="New Development", sqft=400000, num_tenants=0,
        borough="Bronx", neighborhood="South Bronx",
        year_built=2025, floors=18, num_employees=10,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise", "Pilot Fiber"],
        equipment={"hvac": "Daikin VRV IV", "elevator": "Kone — 4 cabs", "security": "HID Origo", "bms": "Johnson Controls OpenBlue", "network_infrastructure": "Cat6a, SMF backbone, Ruckus WiFi 6E"},
        building_summary="Brand new South Bronx development. 18 floors, 400K sqft. Pre-leasing phase. Infrastructure being spec'd now — get into the specs early.",
        tech_signals=["infrastructure spec in progress", "MEP coordination", "tenant fit-out WiFi"],
        sources=["costar", "news"], score=81,
        qualification_notes="Pre-leasing = get into the specs. Partnership with MEP engineer possible.",
    ),
    _lead(
        company_name="L+M Development — Hunts Point",
        company_type="CRE_OPERATOR",
        contact_name="David Chen", contact_title="Project Manager",
        email="d.chen@lmdevpartners.com", phone="(718) 991-8200",
        website="https://lmdevpartners.com",
        address="940 Garrison Avenue, Bronx, NY 10474",
        building_type="Industrial/Food Hub", sqft=600000, num_tenants=40,
        borough="Bronx", neighborhood="Hunts Point",
        year_built=2023, floors=4, num_employees=45,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Industrial cold storage + standard", "elevator": "Freight — 6 cabs", "security": "Genetec + cold chain monitoring", "bms": "Johnson Controls", "network_infrastructure": "Industrial WiFi, Cat6, basic switches"},
        building_summary="Hunts Point food distribution hub. 4 floors, 600K sqft. 40 food industry tenants. Cold chain IoT monitoring needs. Industrial WiFi critical.",
        tech_signals=["cold chain IoT sensors", "industrial WiFi upgrade", "fleet tracking"],
        sources=["nyc_opendata", "costar"], score=73,
        qualification_notes="Specialized food/logistics hub. IoT for cold chain + industrial WiFi. Niche opportunity.",
    ),
    _lead(
        company_name="Brookfield Logistics Bronx",
        company_type="CRE_OPERATOR",
        contact_name="Kevin Murphy", contact_title="Facility Director",
        email="k.murphy@brookfield.com", phone="(718) 860-6000",
        website="https://brookfield.com",
        address="1055 Bronx River Avenue, Bronx, NY 10472",
        building_type="Logistics Center", sqft=900000, num_tenants=10,
        borough="Bronx", neighborhood="Soundview",
        year_built=2020, floors=3, num_employees=80,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios", "Lightpath"],
        equipment={"hvac": "Industrial RTU", "elevator": "Freight — 8 cabs", "security": "Genetec + automated gates", "bms": "Siemens", "network_infrastructure": "Industrial WiFi, fiber backbone, Cisco industrial switches"},
        building_summary="Major logistics center in Soundview. 3 floors, 900K sqft. Brookfield logistics portfolio. High IoT density for warehouse automation.",
        tech_signals=["warehouse automation WiFi", "IoT sensors", "fleet management"],
        sources=["costar", "news", "linkedin"], score=78,
        qualification_notes="Brookfield logistics portfolio. High IoT needs. Industrial WiFi expertise required.",
    ),
]

# =============================================================================
# STATEN ISLAND — 10 leads
# =============================================================================
STATEN_ISLAND = [
    _lead(
        company_name="Empire Outlets",
        company_type="CRE_OPERATOR",
        contact_name="Maria Hernandez", contact_title="General Manager",
        email="m.hernandez@empireoutlets.nyc", phone="(718) 876-8000",
        website="https://empireoutlets.nyc",
        address="55 Richmond Terrace, Staten Island, NY 10301",
        building_type="Retail/Mixed-Use", sqft=340000, num_tenants=35,
        borough="Staten Island", neighborhood="St. George",
        year_built=2019, floors=3, num_employees=25,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Carrier rooftop", "elevator": "Escalators + 2 elevators", "security": "Genetec + analytics", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6, Ruckus APs for public WiFi"},
        building_summary="NYC's only outlet mall at St. George Ferry Terminal. 3 floors, 340K sqft. 35 retail tenants. Public WiFi already deployed but needs upgrade + analytics.",
        tech_signals=["WiFi analytics for foot traffic", "digital signage network", "tenant POS connectivity"],
        sources=["news", "costar"], score=73,
        qualification_notes="Retail WiFi analytics opportunity. 35 tenants for connectivity revenue.",
    ),
    _lead(
        company_name="BFC Partners — St. George",
        company_type="CRE_OPERATOR",
        contact_name="James Richardson", contact_title="Development Director",
        email="j.richardson@bfrpartners.com", phone="(718) 447-8200",
        website="https://bfcpartners.com",
        address="10 Bay Street, Staten Island, NY 10301",
        building_type="Mixed-Use Development", sqft=450000, num_tenants=25,
        borough="Staten Island", neighborhood="St. George",
        year_built=2024, floors=12, num_employees=20,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "Daikin VRF", "elevator": "Otis — 4 cabs", "security": "HID mobile", "bms": "Distech Controls", "network_infrastructure": "Cat6a, fiber risers, Meraki APs"},
        building_summary="New mixed-use development at St. George waterfront. 12 floors, 450K sqft. Modern infrastructure. WiFi-as-a-service from day one.",
        tech_signals=["managed WiFi", "tenant experience app", "smart common areas"],
        sources=["costar", "news"], score=75,
        qualification_notes="New building, modern infra. WiFi revenue model from opening.",
    ),
    _lead(
        company_name="Triangle Equities — Stapleton",
        company_type="CRE_OPERATOR",
        contact_name="Lisa Kapoor", contact_title="Property Manager",
        email="l.kapoor@triangleequities.com", phone="(718) 876-5500",
        website="https://triangleequities.com",
        address="Stapleton Waterfront, Staten Island, NY 10304",
        building_type="Waterfront Mixed-Use", sqft=300000, num_tenants=20,
        borough="Staten Island", neighborhood="Stapleton",
        year_built=2022, floors=8, num_employees=15,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "VRF system", "elevator": "Kone — 3 cabs", "security": "Openpath", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6, Ubiquiti APs"},
        building_summary="Stapleton waterfront development. 8 floors, 300K sqft. Newer building. Looking for building-wide managed WiFi.",
        tech_signals=["managed WiFi", "outdoor WiFi for waterfront", "tenant connectivity"],
        sources=["costar", "marketplace"], score=69,
        qualification_notes="Waterfront development with outdoor WiFi opportunity.",
    ),
    _lead(
        company_name="Matrix Development — St. George",
        company_type="MULTI_TENANT",
        contact_name="Anthony Costa", contact_title="Managing Director",
        email="a.costa@matrixdevelopment.com", phone="(718) 816-4000",
        website="https://matrixdevelopment.com",
        address="120 Stuyvesant Place, Staten Island, NY 10301",
        building_type="Class B Office", sqft=85000, num_tenants=12,
        borough="Staten Island", neighborhood="St. George",
        year_built=1985, floors=6, num_employees=10,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Carrier split systems", "elevator": "Otis — 1 cab", "security": "Basic card reader", "bms": "None", "network_infrastructure": "Cat5e legacy, basic consumer router"},
        building_summary="Class B office near St. George Ferry Terminal. 6 floors, 85K sqft. Legacy infrastructure. Government and professional service tenants.",
        tech_signals=["network upgrade needed", "WiFi for tenants", "security cameras"],
        sources=["nyc_opendata", "web_scraper"], score=56,
        qualification_notes="Legacy building near ferry terminal. Basic upgrade opportunity.",
    ),
    _lead(
        company_name="Garden State Development — New Dorp",
        company_type="MULTI_TENANT",
        contact_name="Robert Benedetto", contact_title="Owner/Manager",
        email="r.benedetto@gsdevelopment.com", phone="(718) 351-2800",
        address="2636 Hylan Boulevard, Staten Island, NY 10306",
        building_type="Medical/Professional Office", sqft=60000, num_tenants=15,
        borough="Staten Island", neighborhood="New Dorp",
        year_built=1995, floors=4, num_employees=8,
        building_isp="Optimum Business", available_isps=["Optimum Business", "Verizon Fios"],
        equipment={"hvac": "Carrier rooftop", "elevator": "Hydraulic — 1 cab", "security": "Basic alarm", "bms": "None", "network_infrastructure": "Cat5e, consumer router, no centralized WiFi"},
        building_summary="Medical/professional office on Hylan Blvd. 4 floors, 60K sqft. 15 medical and professional tenants. HIPAA compliance needs managed network.",
        tech_signals=["HIPAA compliant WiFi", "medical IoT devices", "telehealth bandwidth"],
        sources=["marketplace", "web_scraper"], score=63,
        qualification_notes="Medical tenants need HIPAA-compliant managed WiFi. Compliance sells.",
    ),
    _lead(
        company_name="SI Holding Corp",
        company_type="MULTI_TENANT",
        contact_name="Dennis O'Connor", contact_title="Property Director",
        email="d.oconnor@siholding.com", phone="(718) 984-7800",
        address="100 Richmond Terrace, Staten Island, NY 10301",
        building_type="Class B Office", sqft=100000, num_tenants=18,
        borough="Staten Island", neighborhood="St. George",
        year_built=1975, floors=8, num_employees=12,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Carrier centralized", "elevator": "Dover — 2 cabs", "security": "Key card + cameras", "bms": "Legacy Honeywell", "network_infrastructure": "Cat5e, basic switches, no WiFi"},
        building_summary="Government/office building at St. George. 8 floors, 100K sqft. 18 tenants including city agencies. No building WiFi — tenants use own hotspots.",
        tech_signals=["building WiFi needed", "cable plant upgrade", "security camera IP migration"],
        sources=["nyc_opendata", "marketplace"], score=58,
        qualification_notes="No building WiFi. Tenants using hotspots. Easy win for building-provided WiFi.",
    ),
    _lead(
        company_name="Creative Urban Alchemy",
        company_type="COWORKING",
        contact_name="Aisha Brown", contact_title="Founder & Director",
        email="aisha@creativeurbanalchemy.com", phone="(718) 273-2400",
        website="https://creativeurbanalchemy.com",
        address="481 Bay Street, Staten Island, NY 10304",
        building_type="Coworking/Community Hub", sqft=8000, num_tenants=20,
        borough="Staten Island", neighborhood="Stapleton",
        year_built=2010, floors=2, num_employees=4,
        building_isp="Spectrum Enterprise", available_isps=["Spectrum Enterprise", "Verizon Fios"],
        equipment={"hvac": "Split systems", "elevator": "None", "security": "Smart lock", "bms": "None", "network_infrastructure": "Consumer-grade router, basic WiFi"},
        building_summary="Small community coworking hub in Stapleton. 2 floors, 8K sqft. 20 members. Consumer-grade WiFi. Needs professional managed WiFi.",
        tech_signals=["WiFi upgrade", "video conferencing room", "basic networking"],
        sources=["web_scraper", "marketplace"], score=45,
        qualification_notes="Small community space. Low budget but repeat revenue. Social impact.",
    ),
    _lead(
        company_name="Ironstate Development — St. George",
        company_type="CRE_OPERATOR",
        contact_name="Michael Russo", contact_title="VP of Development",
        email="m.russo@ironstatedevelopment.com", phone="(718) 442-7000",
        website="https://ironstatedevelopment.com",
        address="7 Navy Pier Ct, Staten Island, NY 10304",
        building_type="Waterfront Mixed-Use", sqft=350000, num_tenants=18,
        borough="Staten Island", neighborhood="St. George",
        year_built=2021, floors=10, num_employees=20,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "VRF system", "elevator": "Otis Gen3 — 3 cabs", "security": "HID mobile", "bms": "Distech Controls", "network_infrastructure": "Cat6a, Meraki APs, fiber backbone"},
        building_summary="Waterfront mixed-use at St. George. 10 floors, 350K sqft. Modern infrastructure. Managed WiFi as premium amenity for waterfront lifestyle.",
        tech_signals=["managed WiFi amenity", "smart common areas", "package lockers"],
        sources=["costar", "news"], score=71,
        qualification_notes="Modern waterfront building. WiFi-as-a-service for premium positioning.",
    ),
    _lead(
        company_name="Heritage Property Group",
        company_type="MULTI_TENANT",
        contact_name="Patricia Walsh", contact_title="Building Manager",
        email="p.walsh@heritagepropertygroup.com", phone="(718) 447-3500",
        address="15 Hyatt Street, Staten Island, NY 10301",
        building_type="Professional Office", sqft=45000, num_tenants=10,
        borough="Staten Island", neighborhood="Tompkinsville",
        year_built=1970, floors=4, num_employees=6,
        building_isp="Optimum Business", available_isps=["Optimum Business", "Verizon Fios"],
        equipment={"hvac": "Window units", "elevator": "Hydraulic — 1 cab", "security": "Key lock", "bms": "None", "network_infrastructure": "Cat3 telephone wiring only"},
        building_summary="Small professional office building near ferry. 4 floors, 45K sqft. Zero data infrastructure. Cat3 telephone wiring only. Complete build needed.",
        tech_signals=["complete network install", "WiFi for tenants", "basic security"],
        sources=["nyc_opendata", "marketplace"], score=50,
        qualification_notes="Zero data infra. Complete greenfield build. Small but simple project.",
    ),
    _lead(
        company_name="Flagship Real Estate — Stapleton",
        company_type="MULTI_TENANT",
        contact_name="Chris Morales", contact_title="Operations Manager",
        email="c.morales@flagshipre.com", phone="(718) 876-9200",
        website="https://flagshipre.com",
        address="200 Bay Street, Staten Island, NY 10301",
        building_type="Mixed-Use Commercial", sqft=120000, num_tenants=14,
        borough="Staten Island", neighborhood="Stapleton",
        year_built=2018, floors=6, num_employees=10,
        building_isp="Verizon Fios", available_isps=["Verizon Fios", "Spectrum Enterprise"],
        equipment={"hvac": "VRF system", "elevator": "Otis — 2 cabs", "security": "Openpath", "bms": "Honeywell Niagara", "network_infrastructure": "Cat6, Ubiquiti APs"},
        building_summary="Newer mixed-use in Stapleton. 6 floors, 120K sqft. Modern infrastructure. Looking for managed WiFi provider.",
        tech_signals=["managed WiFi", "tenant portal", "security analytics"],
        sources=["marketplace", "web_scraper"], score=64,
        qualification_notes="Modern building, ready for managed WiFi layer. 14 tenants.",
    ),
]


SAMPLE_LEADS = MANHATTAN + BROOKLYN + QUEENS + BRONX + STATEN_ISLAND


def seed() -> None:
    """Seed the database with sample leads."""
    db = Database()
    existing = db.get_lead_count()
    if existing > 0:
        print(f"Database already has {existing} leads. Skipping seed.")
        return

    for lead in SAMPLE_LEADS:
        db.insert_lead(lead)
    print(f"Seeded {len(SAMPLE_LEADS)} leads.")


if __name__ == "__main__":
    seed()
